version: "3.9"
services:
  dumajobs:
    image: postgres
    container_name: dumajobs-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - dumajobs:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    depends_on:
      - dumajobs
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dumajobs:
